version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: obliga-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: obliga
      POSTGRES_PASSWORD: obliga_password
      POSTGRES_DB: obliga_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
